app/models/user.py
from app.extensions import db
from app.models.products import Products

class User(db.Model):
	__tablename__ = 'user'

	id = db.Column(db.Integer(), autoincrement=True, primary_key=True)
	username = db.Column(db.String(80), unique=True, nullable=False)
	password = db.Column(db.Text, nullable=False)
	dob = db.Column(db.Date, nullable=False)
	phone_number = db.Column(db.Unicode(20), nullable=False)

	product = db.relationship("Products")

	def __init__(self, username, password, dob, phone_number):
		self.username = username
		self.password = password
		self.dob = dob
		self.phone_number = phone_number

app/controllers/home.py
from flask import Blueprint, render_template

blueprint = Blueprint('home', __name__)

@blueprint.route('/')
def index():
	return render_template('home/index.html')

app/controllers/web.py
from flask import Blueprint, render_template

blueprint = Blueprint('web', __name__, url_prefix='/web')


@blueprint.route('/login', methods=["GET"])
def web_login():
	return render_template('user/login.html')

@blueprint.route('/signup', methods=["GET"])
def web_signup():
	return render_template('user/signup.html')

@blueprint.route('/getAllProducts', methods=["GET"])
def web_product():
	return render_template('product/product.html')

@blueprint.route('/viewProduct/<int:product_id>', methods=["GET"])
def web_view_product(product_id):
	return render_template('product/view_product.html',product_id=product_id)

app/templates/user/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Kilofarms Task</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" >
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css') }}" >
    <link rel="stylesheet" href="{{ url_for('static', filename='css/colors.css') }}" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  </head>
  <body>
  	<nav class="navbar navbar-expand-lg navbar-dark bg-gray-dark text-white">
  		<div class="container">
    		<a class="text-white link-reset text-inherit pr-3">
      			Kilofarms Task
    		</a>

    		<div class="collapse navbar-collapse" id="navbarSupportedContent">
      			<ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link text-inherit" href="{{ url_for('home.index') }}">
                    Home
                  </a>
                </li>
          			<li class="nav-item">
            			<a class="nav-link text-inherit" href="{{ url_for('web.web_signup') }}">
              			Signup
            			</a>
          			</li>
      			</ul>
		    </div>
  		</div>
	</nav>
	<div class="login-box">
  		<h2>Login</h2>
  		<form action="#" onsubmit="return false">
    		<div class="user-box">
      			<input type="text" name="username" required="" id="username">
      			<label>Username</label>
    		</div>
    		<div class="user-box">
      			<input type="password" name="password" required="" id="password">
      			<label>Password</label>
    		</div>
    		<button class="btn btn-primary mt-2" onclick="handleOnSubmit()">
      		<span></span>
      		<span></span>
      		<span></span>
      		<span></span>
      			Login
    		</button>
  		</form>
	</div>
  <!-- Scripts for Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/auth.js') }}"></script>
    <script>
      if (isLoggedIn()) {
        window.location.href = "/web/getAllProducts"
      }

    	function handleOnSubmit() {
    		let username = document.getElementById("username").value
    		let password = document.getElementById("password").value

    		login(username, password).then((result) => {
    			if (result.success == false) {
    				alert(result.error)
    			}
    			else
    				window.location.href = "/web/getAllProducts"
    		})

    		return false
    	}
    </script>
  </body>
</html>

app/templates/user/signup.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Kilofarms Task</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" >
    <link rel="stylesheet" href="{{ url_for('static', filename='css/auth.css') }}" >
    <link rel="stylesheet" href="{{ url_for('static', filename='css/colors.css') }}" >
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
  </head>
  <body>
  	<nav class="navbar navbar-expand-lg navbar-dark bg-gray-dark text-white">
  		<div class="container">
    		<a class="text-white link-reset text-inherit pr-3">
      			Kilofarms Task
    		</a>

    		<div class="collapse navbar-collapse" id="navbarSupportedContent">
      			<ul class="navbar-nav ml-auto">
                <li class="nav-item">
                  <a class="nav-link text-inherit" href="{{ url_for('home.index') }}">
                    Home
                  </a>
                </li>
          			<li class="nav-item">
            			<a class="nav-link text-inherit" href="{{ url_for('web.web_login') }}">
              			Login
            			</a>
          			</li>
      			</ul>
		    </div>
  		</div>
	</nav>
	<div class="login-box">
  		<h2>Signup</h2>
  		<form action="#" onsubmit="return false">
    		<div class="user-box">
      			<input type="text" name="username" required="" id="username">
      			<label>Username</label>
    		</div>
        <div class="user-box">
            <input type="date" name="dob" required="" id="dob">
            <label>DOB</label>
        </div>
        <div class="user-box">
            <input type="tel" name="phone_number" required="" id="phone_number">
            <label>Mobile</label>
        </div>
    		<div class="user-box">
      			<input type="password" name="password" required="" id="password">
      			<label>Password</label>
    		</div>
    		<button class="btn btn-primary mt-2" onclick="handleOnSubmit()">
          <span></span>
          <span></span>
          <span></span>
          <span></span>
            Signup
        </button>
  		</form>
	</div>
  <!-- Scripts for Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" ></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="{{ url_for('static', filename='js/auth.js') }}"></script>
    <script>
      if (isLoggedIn()) {
        window.location.href = "/web/getAllProducts"
      }

      function handleOnSubmit() {
        let username = document.getElementById("username").value
        let password = document.getElementById("password").value
        let dob = document.getElementById("dob").value
        let phone_number = document.getElementById("phone_number").value

        signup(username, password, dob, phone_number).then((result) => {
          if (result.success == false) {
            alert(result.error)
          }
          else
            window.location.href = "/web/getAllProducts"
        })

        return false
      }
    </script>
  </body>
</html>